function [] = generateDataSet( sys_par,jj)
%generateDataSet( sys_par,jj) generates compressed data from tick data
%   Inputs: 
%       sys_par: struct generated by getSysPar()
%       jj: index of underlying (if omitted, set to 1)
if nargin < 2;
  jj =1;
end

underlying =    sys_par.underlying{jj};
lengthData =    sys_par.lengthData;
tVec =          sys_par.tVec;
%% check if csv file exists
if exist([underlying,'_tick_',num2str(lengthData),'M.csv'],'file') ~= 2
    disp(['no data available for ',underlying,', length = ',num2str(lengthData),' months'])
    return
end

%% generate variables
var = genvarname([underlying,'_pre']);
data = loadDataCsv([underlying,'_tick_',num2str(lengthData),'M.csv'],sys_par);
eval([var,' = data;'])
for ii = 1:length(tVec)
    var = genvarname([underlying,'_t',num2str(ii)]);
    eval([var,' = compress(',underlying,'_pre,tVec(',num2str(ii),'),sys_par,''bid'',''ask'');']);
end
%%
if size(tVec,2) == 1
    string1 = num2str(tVec');
else
    string1 = num2str(tVec);
end
string1 = string1(~isspace(string1));
%%
save(['./dat/',underlying,num2str(lengthData),'M',string1,'.mat'],[underlying,'*'])
end

